Assembly.MusicApp/Assembly.MusicApp.WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Assembly.MusicApp.WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }

        public void OnPost()
        {

        }
    }
}

Assembly.MusicApp/Assembly.MusicApp.WebApp/Pages/Forms.cshtml.cs
using Assembly.MusicApp.Services.Contracts;
using Assembly.MusicApp.Services.Dtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assembly.MusicApp.WebApp.Pages
{
    public class FormsModel : PageModel
    {
        private readonly IUserService _userService;

        public FormsModel(IUserService userService)
        {
            this._userService = userService;
        }

        public void OnGet() // Init
        {
        }

        public void OnPost()
        {

        }

        public IActionResult OnPostSubmitForm(string name, string email, string description, int age)
        {
            var userDto = new UserDto()
            {
                Name = name,
                Email = email,
                Age = age,
                Description = description,
            };
            var isSuccess = _userService.Add(userDto);

            return RedirectToPage(isSuccess ? "ThankYou" : "Error");
        }
    }
}

Assembly.MusicApp/Assembly.MusicApp.WebApp/Pages/Index.cshtml.cs
using Assembly.MusicApp.Services.Contracts;
using Assembly.MusicApp.Services.Dtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assembly.MusicApp.WebApp.Pages
{
    public class IndexModel : PageModel // ViewModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IUserService _userService;
        public List<UserDto> Users { get; set; }


        public IndexModel(ILogger<IndexModel> logger, IUserService userService)
        {
            _logger = logger;
            this._userService = userService;

        }

        public void OnGet()
        {
            Users = _userService.GetAll();
            //return OkResult("");
            //return RedirectToPage("ThankYou");
        }

        public void OnPost()
        {
            
        }
    }
}

Assembly.MusicApp/Assembly.MusicApp.WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assembly.MusicApp.WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Assembly.MusicApp/Assembly.MusicApp.WebApp/Pages/ThankYou.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assembly.MusicApp.WebApp.Pages
{
    public class ThankYouModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Assembly.MusicApp/Assembly.MusicApp.WebApp/Pages/Forms.cshtml
@page
@model Assembly.MusicApp.WebApp.Pages.FormsModel
@{
}

<main class="forms-container">
    <h1>Welcome to Forms</h1>

    <form method="post" asp-page-handler="SubmitForm">
        <div class="mb-3">
            <label for="name" class="form-label">Enter name</label>
            <input type="text" min=3 max=30 class="form-control" id="name" name="name" placeholder="Enter your name">
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Enter Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>

        <div class="mb-3">
            <label for="age" class="form-label">Enter Age</label>
            <input type="number" class="form-control" id="age" name="age" placeholder="Enter age">
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Example textarea</label>
            <textarea class="form-control" id="description" name="description" rows="3"></textarea>
        </div>

        <input type="submit" />
    </form>

</main>

Assembly.MusicApp/Assembly.MusicApp.WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div>
    <ul class="list-group">
        @foreach(var user in Model.Users)
        {
            <li class="list-group-item">@user.Name</li>
        }
    </ul>
</div>

Assembly.MusicApp/Assembly.MusicApp.WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assembly.MusicApp.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assembly.MusicApp.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Assembly.MusicApp.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Forms">Forms</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assembly.MusicApp.WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Assembly.MusicApp/Assembly.MusicApp.WebApp/Pages/ThankYou.cshtml
@page
@model Assembly.MusicApp.WebApp.Pages.ThankYouModel
@{
}
<h1>THank you</h1>